### ISSUE TITLE
Spherical coordinates

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JuliaApproximation/HarmonicOrthogonalPolynomials.jl#1]
I would hope that we choose theta to be co-latitude (z = cos(theta)) and varphi to be longitude. Seems there is a different choice here?

https://github.com/JuliaApproximation/SphericalHarmonics.jl/blob/7028d27ba92bb289a7d8bd4f241ed4314eb8f2e9/src/SphericalHarmonics.jl#L30-L37

**Comment by MikaelSlevinsky** [comment]
@dlfivefifty (Ping, looks like no one is watching this repository so far.)

**Comment by dlfivefifty** [comment]
You mean swap phi and theta?

**Comment by MikaelSlevinsky** [comment]
Yeah https://juliaapproximation.github.io/FastTransforms.jl/latest/#FastTransforms.sphevaluate

**Comment by dlfivefifty** [comment]
`z = cos(θ)`:

1. [Wikipedia](https://en.wikipedia.org/wiki/Spherical_coordinate_system)
2. [DLMF](https://dlmf.nist.gov/14.30)

`z = cos(φ)`:

1. [Wolfram](https://mathworld.wolfram.com/SphericalCoordinates.html)

I suppose that's a 2-to-1 vote in favour of @MikaelSlevinsky

**Comment by MikaelSlevinsky** [comment]
We could add our upcoming _Acta Numerica_ paper to the first list

**Comment by MikaelSlevinsky** [comment]
FYI, I think i'll be adding spin-weighted spherical harmonic transforms within the next couple months, as well as methods for complex data.

**Comment by dlfivefifty** [comment]
> We could add our upcoming Acta Numerica

Not too late to change it 🤣

**Comment by dlfivefifty** [comment]
@jagot do you agree with Mikael?

**Comment by jagot** [comment]
Yes, I prefer to have `z = r cos(θ)`, I think that is the "physicists convention".

**Comment by dlfivefifty** [comment]
Done.
