### ISSUE TITLE
Tag v0.0.1

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/HarmonicOrthogonalPolynomials.jl#14]
I think we should try to tag ASAP so other packages can start depending on this. What we need to do first:

- [x] Tag ClassicalOrthogonalPolynomials.jl
- [x] Add README
- [ ] Add `Laplacian`

@TSGut How do you feel about trying to tackle the `Laplacian` part? Following https://github.com/JuliaApproximation/MultivariateOrthogonalPolynomials.jl/blob/dd5c05b799014deb9d82286ac264524c7e33c22d/src/Triangle/Triangle.jl#L90 
we probably want to do something like this:
```julia
@simplify function *(Dx::Laplacian, P::SphericalHarmonic)
    ℓ = mortar(Fill.(Base.OneTo(∞), 1:2:∞))
    m = mortar((:).(0:-1:(-∞), 0:∞))
    P * Diagonal(func_of_m_and_ℓ.(m, ℓ))
end
```
so in theory just add the formula to `func_of_m_and_ℓ`. Though I'm sure there will be bugs that I'll have to have a crack at... but a good task if you feel like getting some understanding on how the Infinite block array stuff actually works.

**Comment by TSGut** [comment]
Sounds good, I'll give it a go.

**Comment by TSGut** [comment]
Will submit a PR for the Laplacian soon. Progress is fairly smooth.

Related: Is there a clean way to make block diagonal matrices? I'm aware of the block tridiagonal stuff in InfiniteLinearAlgebra.jl but can't see just diagonals in there. I feel like it would make the package a lot more consistent if we could call the Laplacian using block indices just as with the coefficient vectors. Just feeding a blockvector to Diagonal() unfortunately doesn't seem to preserve block structure? Consider e.g. `Diagonal(mortar(Fill.(-(0:∞)-(0:∞).^2, 1:2:∞)))`.

**Comment by dlfivefifty** [comment]
Awesome!

> `Diagonal(mortar(Fill.(-(0:∞)-(0:∞).^2, 1:2:∞)))`

I'll make this work.

**Comment by dlfivefifty** [comment]
I started it here: https://github.com/JuliaArrays/BlockArrays.jl/pull/151

with this you get block structure:
```julia
julia> using BlockArrays, BandedMatrices, FillArrays

julia> N = 3
3

julia> D = Diagonal(mortar(Fill.(-(0:N)-(0:N).^2, 1:2:2N+1)))
16×16 Diagonal{Int64,BlockArray{Int64,1,Array{Fill{Int64,1,Tuple{Base.OneTo{Int64}}},1},Tuple{BlockedUnitRange{Array{Int64,1}}}}} with indices 1:1:16×1:1:16:
 0  │   ⋅   ⋅   ⋅  │   ⋅   ⋅   ⋅   ⋅   ⋅  │    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅
 ───┼──────────────┼──────────────────────┼───────────────────────────────────
 ⋅  │  -2   ⋅   ⋅  │   ⋅   ⋅   ⋅   ⋅   ⋅  │    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅
 ⋅  │   ⋅  -2   ⋅  │   ⋅   ⋅   ⋅   ⋅   ⋅  │    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅
 ⋅  │   ⋅   ⋅  -2  │   ⋅   ⋅   ⋅   ⋅   ⋅  │    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅
 ───┼──────────────┼──────────────────────┼───────────────────────────────────
 ⋅  │   ⋅   ⋅   ⋅  │  -6   ⋅   ⋅   ⋅   ⋅  │    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅
 ⋅  │   ⋅   ⋅   ⋅  │   ⋅  -6   ⋅   ⋅   ⋅  │    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅
 ⋅  │   ⋅   ⋅   ⋅  │   ⋅   ⋅  -6   ⋅   ⋅  │    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅
 ⋅  │   ⋅   ⋅   ⋅  │   ⋅   ⋅   ⋅  -6   ⋅  │    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅
 ⋅  │   ⋅   ⋅   ⋅  │   ⋅   ⋅   ⋅   ⋅  -6  │    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅
 ───┼──────────────┼──────────────────────┼───────────────────────────────────
 ⋅  │   ⋅   ⋅   ⋅  │   ⋅   ⋅   ⋅   ⋅   ⋅  │  -12    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅
 ⋅  │   ⋅   ⋅   ⋅  │   ⋅   ⋅   ⋅   ⋅   ⋅  │    ⋅  -12    ⋅    ⋅    ⋅    ⋅    ⋅
 ⋅  │   ⋅   ⋅   ⋅  │   ⋅   ⋅   ⋅   ⋅   ⋅  │    ⋅    ⋅  -12    ⋅    ⋅    ⋅    ⋅
 ⋅  │   ⋅   ⋅   ⋅  │   ⋅   ⋅   ⋅   ⋅   ⋅  │    ⋅    ⋅    ⋅  -12    ⋅    ⋅    ⋅
 ⋅  │   ⋅   ⋅   ⋅  │   ⋅   ⋅   ⋅   ⋅   ⋅  │    ⋅    ⋅    ⋅    ⋅  -12    ⋅    ⋅
 ⋅  │   ⋅   ⋅   ⋅  │   ⋅   ⋅   ⋅   ⋅   ⋅  │    ⋅    ⋅    ⋅    ⋅    ⋅  -12    ⋅
 ⋅  │   ⋅   ⋅   ⋅  │   ⋅   ⋅   ⋅   ⋅   ⋅  │    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅  -12

julia> D[Block(2,2)]
3×3 BandedMatrix{Int64} with bandwidths (0, 0):
 -2   ⋅   ⋅
  ⋅  -2   ⋅
  ⋅   ⋅  -2
```

**Comment by dlfivefifty** [comment]
Laplacian can be v0.0.2
