### ISSUE TITLE
Data structure

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JuliaApproximation/HarmonicOrthogonalPolynomials.jl#4]
I'm hoping there will be two equivalent forms of a function on the sphere expanded in spherical harmonics: store the coefficients as a Vector or a Matrix. They are related through a type of data transposition. One form is more convenient than the other for certain operations, but they should both be supported. @dlfivefifty 

In ApproxFun, this would be like supporting `Fun{SphericalHarmonics{Float64}, Matrix{Float64}}` and `Fun{SphericalHarmonics{Float64}, Vector{Float64}}` and conversion routines. I don't know what the data type will be called in quasi-land...

**Comment by dlfivefifty** [comment]
This can be done via a wrapper. For example, the following would do the triangle OPs (with block lengths `1:∞`)
```julia
struct Diagtrav{T,MM <: AbstractMatrix{T}} <: AbstractBlockVector{T}
   data::MM
end

function getindex(A::Diagtrav, K::Block)
   k = Int(K)
   ret = Vector{Float64}(undef, k)
   for j = 1:length(ret)
       ret[j] = A.data[j,k-j+1] 
    end
    ret
end
```

Something similar can be done with spherical harmonics.

**Comment by dlfivefifty** [comment]
Actually it's much better to do it left-to-right, as then its a strided array (with positive stride)!
```julia
function getindex(A::Diagtrav, K::Block)
   k = Int(K)
   s = stride(A.data,2)
   ret[range(k; step=(s-1), length=k)]
end
```
In fact, we can do linear algebra on the blocks without copying have it take advantage of strideness, that is, lower to BLAS.

**Comment by dlfivefifty** [comment]
Note for spherical harmonics I think the negative and non-negative `m` will each be a strided array, but not both together. So they will probably need to use copying, though perhaps we could do a `VcatStridedLayout` to do this in-place.

**Comment by dlfivefifty** [comment]
This is essentially "done" via the `SphereTrav` wrapper
