### ISSUE TITLE
Rename package

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/HarmonicOrthogonalPolynomials.jl#7]
Someone has already registered

https://github.com/jishnub/SphericalHarmonics.jl

Options:

1. SphericalHarmonicsQuasi.jl: though if we rename OrthogonalPolnomialsQuasi.jl to ClassicalOrthogonalPolynomials.jl this is not a good name.
2. HarmonicOrthogonalPolynomials.jl: would match ClassicalOrthogonalPolynomials.jl, etc. and emphasise that we are thinking of them as polynomials in cartesian coordinates
3. HarmonicPolynomials.jl: less verbose version of above though may make it sound algebraic
4. SphericalHarmonicExpansions.jl 
5. Something else

Please vote if you care.

**Comment by TSGut** [comment]
I like (3) HarmonicOrthogonalPolynomials.jl because it matches with the "[Specification]OrthogonalPolynomials.jl" naming scheme used by MultivariateOrthogonalPolynomials.jl, SemiclassicalOrthogonalPolynomials.jl as well as ClassicalOrthogonalPolynomials.jl if the name change happens.

**Comment by dlfivefifty** [comment]
I think I agree 👍

We’d probably then also have ` DiskHarmonic ` and `  BallHarmonic `  for harmonic polynomials in the disk/ball

 we could have a name for higher dimensions...but will anyone ever use more than 3D??

**Comment by MikaelSlevinsky** [comment]
4. is also taken https://github.com/hofmannmartin/SphericalHarmonicExpansions.jl

But I think that packages can be specified by UUID. So if your package ends up being more popular it could be negotiated to take precedence.

Adding tags to a package helps with searchability on GitHub. That helps bring FastTransforms.jl to the top for searching `spherical harmonics` among Julia packages ;).

**Comment by dlfivefifty** [comment]
Let's stick to HarmonicOrthogonalPolynomials.jl for now. This will also help avoid getting a bunch of unwanted users asking for features 😉
